title: Test detectives
hero_image: images/banner.png
description: Learn how to test your code and detect bugs
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "python"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Detective skills
  - title: Assert
  - title: When to assert
  - title: "Challenge: bug detective"
  - title: Logging
  - title: To log or not to log
  - title: "Challenge: log detective"
  - title: Stepping
  - title: "Challenge: step detective"
