---
title: Test detectives
hero_image: images/banner.png
description: Learn how to test your code and detect bugs
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: Introduction
- title: What you will need
  completion: engaged
- title: Detective skills
- title: Assert
- title: When to assert
- title: 'Challenge: bug detective'
- title: Logging
- title: To log or not to log
- title: 'Challenge: log detective'
- title: Stepping
  completion: internal
- title: 'Challenge: step detective'
