---
title: परीक्षण जासूस
hero_image: images/banner.png
description: अपने कोड(code) की जाँच करना और बग्स(bugs) का पता लगाना सीखें
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 4, design-0, programming-4, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: python
site_areas: projects
hardware: ''
software: python
version: 4
last_tested: 2017-01-01
steps:
- title: परिचय
- title: आपको किन चीज़ों की आवश्यकता होगी
  completion: engaged
- title: जासूसी कौशल
- title: दावे के साथ कहना
- title: दावे के साथ कब कहना है
- title: 'चुनौती: बग(bug) जासूस'
- title: लॉगिंग(logging)
- title: लॉग(log) करना है या नहीं करना है
- title: 'चुनौती: लॉग(log) जासूस'
- title: स्टेपिंग(stepping)
  completion: internal
- title: 'चुनौती: स्टेप(step) जासूस'
